### ISSUE TITLE
How to load this extension?

### ISSUE THREAD

**Issue by svaningelgem** [BlitzOffline/StringExpansion#16]
Is it possible to update the README with a section on how to install it?

On PlacerholderAPI wiki it states under ["String"](https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Placeholders#string) that you need to do `/papi ecloud download String`, however this results in an error (no "String" is visible in the tab completion list.

On this page it's called "StringExpansion", but also that is not visible in the tablist.

Thanks for the information.

**Comment by Kaassss** [comment]
I ran into the same problem. I managed to "fix" it by downloading it from https://api.extendedclip.com/expansions/string/ and then put the .jar into the .../PlaceholderAPI/expansions folder myself. (And then restarting the server.)
Is probably not a great long term solution, but works for now.

**Comment by BlitzOffline** [comment]
This issue should be fixed now. The eCloud has a verification system and each update results in the expansion being unverified until someone manually verifies it. This was not done with the last String Expansion update. Non verified expansions can not be download directly in game for security reasons. The String Expansion was verified now.

P.S.: Downloading expansions manually and placing them in the expansions directory is a valid way of installing expansions, however I suggest caution when downloading expansions that are not verified as that means the code was not validated by one of the ecloud moderation team member. There is history of expansions spreading malware which is why the validation system exists.
